// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBa9u41B6pdZ-sQBmj_S2JiOHXB38kZkPQ',
    appId: '1:154970784663:web:6fec03d84e18748daabad2',
    messagingSenderId: '154970784663',
    projectId: 'booking-app-d943c',
    authDomain: 'booking-app-d943c.firebaseapp.com',
    storageBucket: 'booking-app-d943c.firebasestorage.app',
    measurementId: 'G-6YC1HKYGPX',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC8dBRuuEgCs4t9u3WYOc9mrKKL77AkmTI',
    appId: '1:154970784663:android:bbcf7e5490deb66eaabad2',
    messagingSenderId: '154970784663',
    projectId: 'booking-app-d943c',
    storageBucket: 'booking-app-d943c.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCddDlrDT5s3EroO4j-Wn_vXilKZfWhxD4',
    appId: '1:154970784663:ios:20834412a74ae2cbaabad2',
    messagingSenderId: '154970784663',
    projectId: 'booking-app-d943c',
    storageBucket: 'booking-app-d943c.firebasestorage.app',
    iosBundleId: 'com.hoainam.bookingApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCddDlrDT5s3EroO4j-Wn_vXilKZfWhxD4',
    appId: '1:154970784663:ios:c542d9fba3bb298faabad2',
    messagingSenderId: '154970784663',
    projectId: 'booking-app-d943c',
    storageBucket: 'booking-app-d943c.firebasestorage.app',
    iosBundleId: 'com.example.bookingApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBa9u41B6pdZ-sQBmj_S2JiOHXB38kZkPQ',
    appId: '1:154970784663:web:57f329e200eaafecaabad2',
    messagingSenderId: '154970784663',
    projectId: 'booking-app-d943c',
    authDomain: 'booking-app-d943c.firebaseapp.com',
    storageBucket: 'booking-app-d943c.firebasestorage.app',
    measurementId: 'G-C7XRMWK9PB',
  );
}
